from pydantic import BaseModel

from aiteacher.generated.llm import answer_structured_simple


class ErrorDetail(BaseModel):
    incorrect_part: str
    error_description: str
    corrected_part: str

class Errors(BaseModel):
    errors: list[ErrorDetail]


SYS_PROMPT_ERRORS = """You are a language teacher. 
Your task is to check the user's input for any errors in the language the user used. 

You should return a structured response that includes the following information for each error found:
1. The incorrect part: it could be a word, phrase, or sentence.
2. A description of the error.
3. The corrected part.

Ignore punctuation mistakes and the letter capitalization as the input is generated by a speech-to-text system.
Ignore the word "start" in the beginning of the conversation and the word "stop" at the end (they are just to start and stop the recording).
"""

def check_for_errors(query: str) -> str:
    """Check the input text for errors and return a structured response."""
    errs = answer_structured_simple(
        query=query,
        sys_prompt=SYS_PROMPT_ERRORS,
        answer_format=Errors,
    )

    errs_answers = []

    for err in errs.errors:
        errs_answers.append(
            f"You said: '{err.incorrect_part}'. "
            f"This is incorrect. {err.error_description}. "
            f"Corrected part: '{err.corrected_part}'\n"
        )
    return "\n".join(errs_answers)